_target_: robots_realtime.envs.launch.LaunchConfig

sensors:
  cameras:
    top_camera:
          _target_: robots_realtime.sensors.cameras.camera.CameraNode
          camera:
            _target_: robots_realtime.sensors.cameras.zed_camera.ZedCamera
            resolution: "HD720"
            fps: 30
            device_id: "35062621"
            enable_depth: true

robots:
  left: ["robot_configs/franka/franka_robotiq_gripper.yaml"]

agent:
  _target_: robots_realtime.agents.teleoperation.franka_pyroki_viser_agent.FrankaPyrokiViserAgent
  robotiq_gripper: true

station_metadata:
  world_frame: "base"
  arm_type: "franka"
